name: Compilation Image Docker

on:
  push:
    branches:
      - '**'

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clôner le dépôt
        uses: actions/checkout@v4
      - name: Mise en place de Docker Buildx
        uses: docker/setup-buildx-action@v3      	
      - name: Authentification au registre de Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compilation de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true