name: Compilation Native Image Docker

on:
  push:
    branches:
      - '**'

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clôner le dépôt
        uses: actions/checkout@v4

      - name: Mise en place de Docker Buildx
      	uses: docker/setup-buildx-action@v3

      - name: Compilation de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.native
          tags:turbo-umbrella-native:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
